name: pic_connect
description: Explore and connect through photography.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  advstory: ^0.2.1
  awesome_snackbar_content: ^0.1.3
  cached_network_image: ^3.2.3
  camera: ^0.10.5+2
  camerawesome: ^2.0.0-dev.1
  card_swiper: ^3.0.1
  carousel_slider: ^4.2.1
  chewie: ^1.7.0
  cloud_firestore: ^4.8.1
  country_picker: ^2.0.21
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  easy_image_viewer: ^1.2.1
  equatable: ^2.0.5
  file_picker: ^5.3.0
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  firebase_storage: ^11.2.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_chat_types: ^3.6.1
  flutter_chat_ui: ^1.6.8
  flutter_firebase_chat_core: ^1.6.7
  flutter_keyboard_visibility: ^5.4.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.1
  flutter_spinkit: ^5.2.0
  flutter_staggered_grid_view: ^0.6.2
  flutter_svg: ^2.0.7
  freezed_annotation: ^2.4.1
  geocoding: ^2.1.0
  geolocator: ^10.0.0
  get_it: ^7.6.0
  go_router: ^9.0.3
  http: ^0.13.6
  image_editor_plus: ^0.2.5
  image_picker: ^1.0.0
  intl: ^0.18.0
  mime: ^1.0.4
  mockito: ^5.4.2
  open_filex: ^4.3.2
  path_provider: ^2.1.1
  provider: ^6.0.1
  share_plus: ^7.1.0
  textfield_tags: ^2.0.2
  uuid: ^3.0.5
  video_player: ^2.7.0
  video_thumbnail: ^0.5.3
  visibility_detector: ^0.4.0+2  

dev_dependencies:
  build_runner: ^2.3.3
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  json_annotation: ^4.8.1
  welltested:
    git:
      url: https://github.com/Welltested-AI/welltested-cli.git
  bloc_test:

dependency_overrides:
  extended_image: ^8.1.1
  http: ^1.1.0
  welltested_annotation:
    git:
      url: https://github.com/Welltested-AI/welltested_annotation.git


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/pic_connect_logo.svg
    - assets/pic_connect_onboarding_video.mp4
    - assets/app_icon.png
    - assets/sign_in_background_picture.jpg
    - assets/user_default_icon.png
    - assets/sign_up_background_picture.jpg
    - assets/capture_and_share_moments.png
    - assets/connect_people.png
    - assets/discover_inspiration.png
    - assets/welcome_camera.png
    - assets/sign_out.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  fonts:
    - family: montserrat
      fonts:
        - asset: assets/fonts/montserrat_black.ttf
          weight: 900
        - asset: assets/fonts/montserrat_extra_bold.ttf
          weight: 800
        - asset: assets/fonts/montserrat_bold.ttf
          weight: 700
        - asset: assets/fonts/montserrat_semi_bold.ttf
          weight: 600
        - asset: assets/fonts/montserrat_medium.ttf
          weight: 500
        - asset: assets/fonts/montserrat_regular.ttf
          weight: 400
        - asset: assets/fonts/montserrat_thin.ttf
          weight: 300
        - asset: assets/fonts/montserrat_light.ttf
          weight: 200
        - asset: assets/fonts/montserrat_extra_light.ttf
          weight: 100
