name: run-flutter-test
on: 
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  drive:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: subosito/flutter-action@v1
    - run: flutter test
